### ISSUE TITLE
crashes on initialization

### ISSUE THREAD

**Issue by sekomer** [bones-ai/rust-drive-ai#7]
on M1 silicon MacBook, app crashes after after running

```    bash
Finished `release` profile [optimized] target(s) in 0.14s
     Running `target/release/steering`
2024-07-26T14:00:02.857264Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Pro", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2024-07-26T14:00:02.971056Z  INFO bevy_prototype_debug_lines: Loaded 2d debug lines plugin.
2024-07-26T14:00:02.981619Z  INFO bevy_winit::system: Creating new window "Bevy App" (0v0)
2024-07-26 17:00:03.112 steering[78715:8272772] CAMetalLayer ignoring invalid setDrawableSize width=4294967295.000000 height=4294967295.000000
2024-07-26T14:00:03.113864Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default
thread 'Compute Task Pool (0)' panicked at /Users/blackbird/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.15.1/src/backend/direct.rs:3024:5:
wgpu error: Validation Error

Caused by:
    In Device::create_texture
      note: label = `main_texture_a`
    Dimension X value 4294967295 exceeds the limit of 16384


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (1)' panicked at /Users/blackbird/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:194:60:
A system has panicked so the executor cannot continue.: RecvError
thread '<unnamed>' panicked at /Users/blackbird/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.10.1/src/task_pool.rs:376:49:
called `Option::unwrap()` on a `None` value
thread 'main' panicked at /Users/blackbird/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.10.1/src/pipelined_rendering.rs:136:45:
called `Result::unwrap()` on an `Err` value: RecvError
thread 'main' panicked at /Users/blackbird/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.10.1/src/task_pool.rs:376:49:
called `Option::unwrap()` on a `None` value

/tmp/rust-drive-ai main* ❯                                             17:00:03
```

**Comment by sekomer** [comment]
seems like `bevy` is the bad guy, `cargo update` fixed the problem
